name: Continuous Integration
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  scalafmt:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          apps: scalafmt sbtn
      - run: scalafmt --test
      - run: sbtn scalafixAll -test
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jvm: ['adopt:1.8', 'adopt:1.11', 'temurin:1.17']
    name: Test on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/setup-action@v1.2.0-M3
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - run: sbt test
    - run: sbt scripted
